# Generated by Django 3.1.2 on 2020-10-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201005_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='descrição',
            new_name='description',
        ),
    ]
