# Generated by Django 3.1.2 on 2020-10-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201005_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='description',
            new_name='descrição',
        ),
    ]
